### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sfdrada** [paulphys/task-completion#1]
Hey paulphys,

Really like the idea of your plugin but have had trouble setting it up. Would you be willing to update this plugin or release it in the community plugins marketplace.

Let me know if you need any help,
Sage

**Comment by paulphys** [comment]
Hi Sage,
unfortunately the plugin isn't finished yet. If you take look at [main.ts](https://github.com/paulphys/task-completion/blob/master/main.ts), you would see that it is basically just the obsidian plugin template. If I recall correctly, I continued working on this locally, it's just not pushed onto GitHub yet. Still planning on finishing it someday tho, but I'm just not using Obsidian at the moment.

Best,
Paul

**Comment by sfdrada** [comment]
No problem, I am currently developing my own so you can remove the project off your todo's. If you ever switch back to Obsidian feel free to give it a try.

Thanks for your time,
Sage

**Comment by paulphys** [comment]
That's nice to hear. Feel free to notify me once it's released, would love to check it out.

Best,
Paul

**Comment by sfdrada** [comment]
Got it released, hope you enjoy!
